name: Add bugs to bugs project

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@RELEASE_VERSION
        with:
          # You can target a project in a different organization
          # to the issue
          project-url: https://github.com/users/dani-tweig/projects/1
          github-token: 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
          labeled: bug, needs-triage, type/epic
          label-operator: OR
