name: Auto Assign to Project(s)
# https://github.com/marketplace/actions/assign-to-one-project

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]
env:
  MY_GITHUB_TOKEN: ${{ secrets.DANI_GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
  #  - name: Assign NEW issues and NEW pull requests to project 2
  #    uses: srggrs/assign-one-project-github-action@1.2.1
  #    if: github.event.action == 'opened'
  #    with:
  #      project: 'https://github.com/srggrs/assign-one-project-github-action/projects/2'

    - name: Assign issues and pull requests with `bug` label to project 3
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: |
        contains(github.event.issue.labels.*.name, 'type/bug') ||
        contains(github.event.pull_request.labels.*.name, 'type/bug')
      with:
        project: 'https://github.com/users/dani-tweig/projects/1'
        column_name: 'Backlog'
