name: Urgent Issue Reminder

on:
  schedule:
    - cron: '*/15 * * * *' 

jobs:
  reminder:
    runs-on: ubuntu-latest

    steps:
    - name: Send reminders
      uses: actions/github-script@v7
      with:
        script: |
          const labelFilters = [ 'type/bug'];
          const excludingLabelFilters = ['documentation', 'type/longterm'];
          const daysInactive = 2;
          const now = new Date();

          // Fetch open issues
          const issues = await github.rest.issues.listForRepo({
            owner: context.repo.owner,
            repo: context.repo.repo,
            state: 'open'
          });

          for (const issue of issues.data) {
            // Check if issue has any of the specified labels
            const hasFilteredLabel = issue.labels.some(label => labelFilters.includes(label.name));
            const hasExcludingLabel = issue.labels.some(label => excludingLabelFilters.includes(label.name));
            if (hasExcludingLabel) continue;
            if (!hasFilteredLabel) continue;

            // Check for inactivity
            const lastUpdated = new Date(issue.updated_at);
            const diffInDays = (now - lastUpdated) / (1000 * 60 * 60 * 24);
            if (diffInDays > daysInactive) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                body: `@${context.issue.assignees} This urgent issue had no activity for more than ${daysInactive} days. Please check its status.\n CC`
              });
            }
          }
